language: cpp

script: make test

matrix:
  include:
    - os: linux
      dist: xenial
      compiler: clang
      name: "Linux clang 7"
    - os: osx
      osx_image: xcode10.1
      name: "Macos xcode 10.1"
    - os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
      name: "Linux gcc 7"
    - os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
      name: "Linux gcc 8"
    - os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - llvm-toolchain-xenial-8
          packages:
            - clang-8
      env:
        - MATRIX_EVAL="CC=clang-8 && CXX=clang++-8"
      name: "Linux clang 8"
        
before_install:
    - eval "${MATRIX_EVAL}"
